#!/bin/python3

import subprocess
import sys
import math
from table import *

if (sys.version_info.major * 10 + sys.version_info.minor) < 35:
        raise Exception("Python 3.5 or a more recent version is required.")


class Clasp:
    @staticmethod
    def _cnf_format(variable_count, clauses):
        """ Description
        Format a list of prepositions to clasp format.
        Ex.
        p cnf 3 2
        -1 -3 0
        -2 -3 0
        """    
        cnf = 'p cnf {0} {1}\n'.format(variable_count, len(clauses))        

        for i in clauses:
            for j in i:
                cnf += '{} '.format(j)
            cnf += '0\n'

        return cnf.encode('utf-8')

    @staticmethod
    def resolve(variable_count, clauses, max_solutions=0):
        cnf = Clasp._cnf_format(variable_count, clauses)
        # Execute clasp with cnf string as input
        cp = subprocess.run(
            ['clasp', '--verbose=0', '{0}'.format(max_solutions)], 
            input=cnf,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )

        stderr = str(cp.stderr, encoding='utf-8')
        stdout = str(cp.stdout, encoding='utf-8')

        # Raise a exception if stderr is not empty
        if len(stderr) != 0:
            raise Exception('{}\n{}'.format(cnf, stderr))

        # Parse the solutions
        result = None
        solutions = []
        lines = stdout.split('\n')
        row = []
        for line in lines:
            if line.startswith('v '):
                tmp = list(map(int, line[2:].split(' ')))

                # Only when the line ends with 0 is a full solution
                # else is a partial solution
                if tmp[-1] == 0:
                    row.extend(tmp[:-1])
                    solutions.append(row)
                    row = []
                else:
                    row.extend(tmp)

            elif line.startswith('s '):
                result = line[2:]
                break
        
        return solutions, result
    

# Note: Negatives values are white and
# positive values are black
#
# white = 0 with values < 0
# black = 1 with values > 0
def rule_table(t):
    row = []

    for i, value in enumerate(t.data()):
        if value == '0':
            row.append([-(i + 1)])
        elif value == '1':
            row.append([i + 1])
    return row


def rule_1_base(rows, row, cnt, size):
    if len(row) > 2:
        if row[-1] < 0 and row[-2] < 0 and row[-3] < 0:
            return        
        if row[-1] > 0 and row[-2] > 0 and row[-3] > 0:
            return
    
    if len(row) == size and cnt != 0:
        return

    if len(row) == size:
        rows.append(row)
        return

    if cnt != 0:               
        rule_1_base(rows, row + [1], cnt - 1, size)

    row.append(-1)
    rule_1_base(rows, row, cnt, size)

# This function generates the rule to check that in each row and column there is the same number of 0 and 1
#
# Cases not in permutations of
# |0|0|0|1|1|1|
#
def rule_1(size):
    cnt = size // 2
    rows = []

    # Base row generation
    base = []
    for i in range(0, cnt):
        rule_1_base(base, [], i, size)

    for i in base:        
        for w in range(0, size):
            # Generate rows base
            # Generate columns base
            row = []
            col = []
            for j, k in enumerate(i):
                row.append(i[j] * (j + 1 + w * size))
                col.append(k * (j * size + 1 + w))
            rows.append(row)                
            rows.append(col)
            
            row = row.copy()
            col = col.copy()
            for j in range(0, size):
                row[j] *= -1
                col[j] *= -1
            rows.append(row)
            rows.append(col)

    return rows


# This function generates the rule to check that in each row and column there are not 3 or more like symbols stuck together
#
# |0|0|0|x|x|x|
# |x|0|0|0|x|x|
# |x|x|0|0|0|x|
# |x|x|x|0|0|0|
def rule_2(size):
    assert size > 1, 'size too small'

    if size < 3:
        return []
    
    rows = []
    cols = []

    for index in range(0, size):
        # Row index rules
        for i in range(index * size, index * size + size - 3 + 1):
            row = []
            for j in range(0,  3):
                row.append(i + j + 1)

            rows.append(row)
            rows.append(list(map(lambda x: -x, row)))

        # Column index rules
        for i in range(0, size - 3 + 1):
            col = []
            for j in range(0,  3):
                col.append((i + j) * size + index + 1)

            cols.append(col)
            cols.append(list(map(lambda x: -x, col)))

    rows.extend(cols)
    return rows

def propositional_logic(atm, num1, num2):
    clauses = []
    clauses.append([-atm, num1, num2])
    clauses.append([-atm, -num1, -num2])
    clauses.append([atm, -num1, num2])
    clauses.append([atm, num1, -num2])
    return clauses

# This function generates the rule to check that there are no equal rows or columns
#
# |1|0|0|1|0|1|
# |x|x|x|x|x|x|
# |1|0|0|1|0|1|
# |0|x|x|0||x|
def rule_3(table):
    size = table.size()
    count = size * size
    clauses = []
    for k in range(0, size - 1):
        for i in range(k + 1, size):
            for j in range(0, size):
                count += 1
                clauses.extend(propositional_logic(count, j + size * k + 1, j + size * i + 1))
                count += 1
                clauses.extend(propositional_logic(count, j * size + k + 1, j * size + i + 1))
            clauses.append(list(range(count-size * 2 + 1, count, 2)))
            clauses.append(list(range(count-size * 2 + 2, count, 2)))
               
    return count, clauses

def equals_row(n, a, b):
    for i in range(0, n):
        if a[i] != b[i]:
            return False
    return True

def pass_rule_1(n, t):
    nh = n // 2
    passed = True
    for i in range(0, n):
        # Rows
        count = len(list(filter(lambda x: x == '0', t.get_row(i))))
        if count != nh:
            #print('Zero count at row {} is: {} != {}'.format(i + 1, count, nh))
            passed = False

        count = len(list(filter(lambda x: x == '0', t.get_col(i))))
        if count != nh:
            #print('Zero count at column {} is: {} != {}'.format(i + 1, count, nh))
            passed = False
    return passed

def pass_rule_2(n, t):
    passed = True
    for i in range(0, n):
        row = t.get_row(i)
        col = t.get_col(i)

        for j in range(0, n - 2):                
            if (row[j] == '0' and row[j + 1] == '0' and row[j + 2] == '0') or (row[j] == '1' and row[j + 1] == '1' and row[j + 2] == '1'):
                #print('Consecutive colors at row {}, index: {}'.format(i + 1, j))
                passed = False

            if (col[j] == '0' and col[j + 1] == '0' and col[j + 2] == '0') or (col[j] == '1' and col[j + 1] == '1' and col[j + 2] == '1'):
                #print('Consecutive colors at column {}, index: {}'.format(i + 1, j))
                passed = False

    return passed

def pass_rule_3(n, t):
    def equals(n, a, b):
        for i in range(0, n):
            if a[i] != b[i]:
                return False
        return True

    passed = True
    for i in range(0, t.size()):
        for j in range(0, t.size()):
            if i != j and equals(n, t.get_row(i), t.get_row(j)):
                #print('Rule3 test failed at rows: {}, {}'.format(i + 1, j + 1))
                passed = False
            if i != j and equals(n, t.get_col(i), t.get_col(j)):
                #print('Rule3 test failed at columns: {}, {}'.format(i + 1, j + 1))
                passed = False
    return passed


if __name__ == "__main__":
    if len(sys.argv) != 2 :
        print("Usage: binairo <filename>")
        exit(-1)

    t = Table.from_file(sys.argv[1], Table.from_text)

    print('Size: {}'.format(t.size()))
    print('{}'.format(t))
    print('')

    size = t.size()
    rules = []

    # Initial state rule
    rules.extend(rule_table(t))

    # The three conditions rules
    rules.extend(rule_1(size))
    rules.extend(rule_2(size))
    variable_count, clauses = rule_3(t)
    rules.extend(clauses)

    solutions, result = Clasp.resolve(
        variable_count, # Number of variables
        rules,
        max_solutions=0
    )

    errors = [0, 0, 0]
    for i in range(0, len(solutions)):
        print('Solution: {}'.format(i + 1))
        t = Table.from_values(solutions[i][0: size * size])
        print('{}'.format(t))

        if not pass_rule_1(size, t):
            errors[0] += 1

        if not pass_rule_2(size, t):
            errors[1] += 1

        if not pass_rule_3(size, t):
            errors[2] += 1
        
        print('')

    print('Result: {}'.format(result))
    for i, j in enumerate(errors):
        print('Not passed rule {}: {}'.format(i + 1, j))